package macos

import (
	"strconv"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestTheCheckedInFactsTableIsSound(t *testing.T) {
	require.NoError(t, Table().Check())
	require.NotEmpty(t, Table().Facts, "facts.json is generated by tools/facts, never empty")
	for _, release := range Known() {
		_, ok := Table().Lookup(release.Darwin, "arm64", ProfileTools)
		require.True(t, ok, "dockhand's base image for Darwin %d is in the table", release.Darwin)
	}
}

func TestLookupPrefersATartImageToABuildbot(t *testing.T) {
	buildbot := Facts{Darwin: 25, Architecture: "arm64", Profile: ProfileXcode, Xcode: "26.6", Tools: "26.6", Source: Source{Kind: SourceBuildbot, From: "ports-26_arm64-builder build 1", Date: "2026-09-26"}}
	image := buildbot
	image.Source = Source{Kind: SourceTart, From: "dockhand-xcode-tahoe", Date: "2026-09-25"}
	table := FactsTable{Facts: []Facts{buildbot, image}}
	got, ok := table.Lookup(25, "arm64", ProfileXcode)
	require.True(t, ok)
	require.Equal(t, image, got)
	_, ok = table.Lookup(25, "arm64", ProfileTools)
	require.False(t, ok)
}

func TestCheckRefusesAnUnsoundRow(t *testing.T) {
	good := Facts{Darwin: 25, Architecture: "arm64", Profile: ProfileTools, Xcode: "none", Tools: "26.6", Clang: "2100.1.1.101", Source: Source{Kind: SourceTart, From: "dockhand-base-tahoe", Date: "2026-09-25"}}
	require.NoError(t, FactsTable{Facts: []Facts{good}}.Check())
	for _, change := range []func(*Facts){
		func(f *Facts) { f.Architecture = "" },
		func(f *Facts) { f.Profile = "full" },
		func(f *Facts) { f.Tools = "" },
		func(f *Facts) { f.Xcode = "26.6" },
		func(f *Facts) { f.Source.Kind = "memory" },
		func(f *Facts) { f.Source.Date = "" },
		func(f *Facts) { f.Clang = "clang-2100" },
	} {
		bad := good
		change(&bad)
		require.Error(t, FactsTable{Facts: []Facts{bad}}.Check(), "%+v", bad)
	}
	generation := Generation{Darwin: 25, Tools: 26, Source: Source{Kind: SourceBuildbot, From: "ports-26_arm64-builder build 1", Date: "2026-09-26"}}
	require.NoError(t, FactsTable{Generations: []Generation{generation}}.Check())
	require.Error(t, FactsTable{Generations: []Generation{generation, generation}}.Check(), "a release has one generation")
	unsourced := generation
	unsourced.Source.Date = ""
	require.Error(t, FactsTable{Generations: []Generation{unsourced}}.Check())
}

// Every release setup builds has a tools generation in the table, the one
// its arm64 builder runs, and dockhand's images carry that generation: a
// row whose tools are of another generation is an image setup didn't pin,
// as the Tahoe images were before 2026-09-25.
func TestEveryReleaseHasItsToolsGenerationAndTheImagesKeepIt(t *testing.T) {
	for _, release := range Known() {
		require.NotZero(t, release.Tools, "Darwin %d has a tools generation", release.Darwin)
	}
	for _, facts := range Table().Facts {
		if facts.Source.Kind != SourceTart || facts.Tools == "none" {
			continue
		}
		generation, ok := Table().Generation(facts.Darwin)
		require.True(t, ok, facts.Source.From)
		major, _, _ := strings.Cut(facts.Tools, ".")
		require.Equal(t, strconv.Itoa(generation), major, "%s has tools %s, of generation %d", facts.Source.From, facts.Tools, generation)
	}
}
