package publish

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/herbygillot/dockhand/internal/darwin/abi"
	"github.com/herbygillot/dockhand/internal/record"
)

// A VERIFIED BODY VOUCHES FOR WHAT THE RECORD REMEMBERS, in the shape of
// macports-ports' own pull request template, with the boxes dockhand can
// honestly answer checked and the ones it could not have answered
// deleted.
// yes is a port that declares an enabled test command.
var yes = true

func TestAVerifiedBodyStatesTheEvidenceAndChecksWhatItCanVouchFor(t *testing.T) {
	lint := "clean"
	f := facts(func(f *Facts) {
		f.Attempts[0].Runs = map[string]record.Run{"jq": {
			State: record.Passed, Content: "tree-1", At: clock,
			Ask: record.Ask{Test: true, FromSource: true}, HasTests: &yes,
			Lint: &lint,
		}}
		f.Change.ClosesTicket = "12345"
		f.Change.Riders = []string{"a modeline"}
	})
	out := body(f, "1.2.3")

	assert.Contains(t, out, "Build **verified** at commit")
	// The environment words the claim; the two qualifiers this run earned
	// attach to the ACT the claim opens with, not to its tail.
	assert.Contains(t, out, "Sequoia: linted clean, built from source and tested in a pristine VM.")
	assert.Contains(t, out, "###### Tested on\n- macOS Sequoia — built in a pristine VM, via dockhand\n")
	assert.Contains(t, out, "Written against the ports tree as of 2026-09-07.")
	assert.Contains(t, out, "Also: a modeline.\n")
	assert.Contains(t, out, "Closes: https://trac.macports.org/ticket/12345\n")
	assert.Contains(t, out, "- [x] checked your Portfile with `port lint`?")
	assert.Contains(t, out, "- [x] tried existing tests with `sudo port test`?")
	assert.Contains(t, out, "- [x] tried a full install with")
	assert.Contains(t, out, "referenced existing tickets on [Trac]")
	assert.Contains(t, out, "[dockhand](https://github.com/herbygillot/dockhand) 1.2.3\n")

	// A single subject's lines are not prefixed with its own port: the
	// pull request is about that port and its title says so.
	assert.NotContains(t, out, "jq on Sequoia")
}

// A BODY WITH NOTHING TO SAY ABOUT A RUN SAYS WHICH OF THE SEVERAL
// POSSIBLE REASONS IS ITS OWN. The shipped body printed "no verification
// environment on the submitting machine" for every one of them.
//
// A BRANCH-BOUND CHANGE IS THE EXCEPTION: it states its provenance
// rather than a reason. The reason it used to state was --no-verify, and
// record.ToBranch is not only --no-verify however its doc reads —
// app.destination returns it for an ordinary Enqueue too. Measured: a
// bump on a machine with no tart published that it had been minted with
// a flag nobody typed. What dockhand did and what the branch is are true
// of both, and answer the reviewer's actual question.
func TestAnUnverifiedBodyNamesItsOwnCause(t *testing.T) {
	noVerify := facts(func(f *Facts) {
		f.Change.Destination = record.ToBranch
		f.Attempts = nil
	})
	out := body(noVerify, "")
	assert.Contains(t, out,
		"Generated by [dockhand](https://github.com/herbygillot/dockhand) - not pre-verified")
	assert.NotContains(t, out, "--no-verify", "no reason is asserted that this arm cannot know")

	nothingRun := facts(func(f *Facts) { f.Attempts = nil })
	assert.Contains(t, body(nothingRun, ""),
		"Not verified: nothing has been run for this commit's content.")

	// A COHORT COMMIT INHERITS THE HEADLINE'S VERIFICATION BY DESIGN and
	// carries no runs over its own content. Evidence is keyed by CONTENT
	// now, so the body can tell this from "nothing was ever run" — which is
	// the pair the shipped body could not, and it published "nothing was
	// run" directly above an ABI measurement.
	extended := facts(func(f *Facts) {
		f.Change.Content = "tree-2"
		f.Attempts[0].Content = "tree-1"
	})
	assert.Contains(t, body(extended, ""),
		"this commit adds to a change that was verified at `aaaa`, and its own verification has not come back.")
}

// THE THREE RUN-DERIVED BOXES ARE DELETED WHERE NOTHING RAN. An
// unchecked box under "Have you" says a step was available and not
// taken; printing one for a step that was never on offer is a false
// implication that costs a reviewer real attention.
func TestTheRunBoxesAreDeletedRatherThanLeftUnticked(t *testing.T) {
	out := body(facts(func(f *Facts) { f.Attempts = nil }), "")
	assert.NotContains(t, out, "port lint")
	assert.NotContains(t, out, "sudo port test")
	assert.NotContains(t, out, "pristine VM")
	// And the two questions dockhand can never answer are gone for good.
	assert.NotContains(t, out, "basic functionality")
	assert.NotContains(t, out, "most important variants")
}

// A FAILURE IS NEVER LOCAL TO THIS MACHINE. A member can be proven on
// one platform and failed on another and the change still publish, since
// the dependents are best effort — and then the failure is the one line
// a reviewer most needs, on the body that is otherwise vouching. Found
// live: a body that listed gegl's pass on Sonoma and simply omitted its
// failure on Sequoia.
func TestAVerifiedBodyStillStatesAFailureOnAnotherPlatform(t *testing.T) {
	sonoma := func(state record.RunState) func(*Facts) {
		return func(f *Facts) {
			f.Attempts = append(f.Attempts, record.Attempt{
				ID: "att-2", Change: "chg-1", Sha: "aaaa", Content: "tree-1",
				Platform: "Sonoma", Phase: record.Finished, Started: clock,
				Runs: map[string]record.Run{
					"jq":     {State: record.Passed, At: clock},
					"libfoo": {State: state, At: clock},
				},
			})
		}
	}
	f := cohortFacts(record.Accepted)
	sonoma(record.Failed)(&f)
	out := body(f, "")
	assert.Contains(t, out, "Build **verified** at commit")
	assert.Contains(t, out, "libfoo on Sonoma: the build failed, and this was published anyway.")

	// A run that is merely this machine's afternoon IS kept local, for a
	// subject already proven elsewhere.
	f = cohortFacts(record.Accepted)
	sonoma(record.Canceled)(&f)
	out = body(f, "")
	assert.Contains(t, out, "Build **verified** at commit")
	assert.NotContains(t, out, "libfoo on Sonoma:")
}

// A COHORT'S LINES NAME THEIR SUBJECT, because "Sequoia: built in a
// pristine VM" said nine times over is a claim about nine different
// ports that reads as one repeated nine times.
func TestACohortsEvidenceLinesNameTheirMember(t *testing.T) {
	out := body(cohortFacts(record.Accepted), "")
	assert.Contains(t, out, "jq on Sequoia:")
	assert.Contains(t, out, "libfoo on Sequoia:")
}

// THE COHORT SECTION RESTATES THE CRITERION VERBATIM AND CARRIES THE
// CAVEAT BESIDE IT. One sentence in the commit body, the pull request
// and the terminal line, made once in the judgment rather than reworded
// per audience — which is the whole argument for a proposal: a person
// can check the one claim behind it with otool by hand.
func TestTheCohortSectionQuotesTheCriterionAndItsLimits(t *testing.T) {
	out := body(cohortFacts(record.Accepted), "")
	assert.Contains(t, out, "install name libjq.1.dylib -> libjq.2.dylib.")
	assert.Contains(t, out, abi.Limits+".")
	assert.Contains(t, out, "Revision bumped in this change:")
	assert.Contains(t, out, "  — libfoo (devel/libfoo): links libjq; /opt/local/bin/foo -> libjq.1.dylib\n")
	// The ports examined and left out are printed with the reason: a
	// decision no reader can see is a decision nobody can disagree with.
	assert.Contains(t, out, "\n"+listedHeader+"\n")
	assert.Contains(t, out, "  — libbar (devel/libbar): build-only dependent\n")
}

// A PROPOSAL STILL OPEN IN A PUBLISHED BODY IS A PERSON HAVING PUBLISHED
// PAST THEIR OWN ADVISORY, which is theirs to do and worth saying out
// loud rather than dressing up as a cohort. A dismissed one says so too.
func TestAnUnansweredOrDismissedProposalIsStated(t *testing.T) {
	assert.Contains(t, body(cohortFacts(record.Proposed), ""),
		"1 dependent needs a revision bump (libfoo) was proposed and is not in this change.")
	assert.Contains(t, body(cohortFacts(record.Dismissed), ""),
		"1 dependent needs a revision bump (libfoo) was proposed and dismissed by hand.")
}

// A MEMBER THE BODY CLAIMS A BUMP FOR IS NEVER LISTED WITH NOTHING
// BESIDE IT: the reviewer reading "Revision bumped in this change" is
// owed either the evidence or the reason there is none, on the same
// line.
func TestAMemberWithNoProofSaysWhy(t *testing.T) {
	f := cohortFacts(record.Accepted)
	f.Attempts[0].Runs["libfoo"] = record.Run{State: record.Failed, At: clock}
	assert.Contains(t, body(f, ""),
		"  — libfoo (devel/libfoo): links libjq; the build failed, so nothing was measured\n")

	// Nobody looked, and it is not the member's own doing: the silence
	// stands, because the reason is stated once elsewhere.
	f = cohortFacts(record.Accepted)
	f.Attempts[0].Runs["libfoo"] = record.Run{State: record.Passed, At: clock}
	assert.Contains(t, body(f, ""), "  — libfoo (devel/libfoo): links libjq\n")

	// The sweep ran and found no binding: the port is build-only in fact
	// whatever its depends_* fields said, and the revbump was still spent.
	f = cohortFacts(record.Accepted)
	f.Attempts[0].Runs["libfoo"] = record.Run{State: record.Passed, At: clock, Links: []string{}}
	assert.Contains(t, body(f, ""), "links nothing that moved")
}

// THE MAINTAINER'S OWN WORDS ARE QUOTED VERBATIM AND FENCED, because a
// quote that was reflowed is not verbatim — and because a PORTFILE
// COMMENT STARTS WITH "#".
//
// It used to indent by two spaces, which Markdown reads as ordinary
// prose rather than as a code block (that needs four). So every line of
// a quoted instruction rendered as an H1 HEADING: the whole maintainer's
// comment, on live pull request #34567, in title-sized type. Four spaces
// would fix the size and still let the renderer re-wrap bytes this is
// promising not to touch; a fence says "these are bytes from a file" to
// the renderer as well as to the reader.
func TestAnInstructionCommentIsQuotedInAFenceAndNeverAsAHeading(t *testing.T) {
	f := facts(func(f *Facts) {
		f.Change.Findings = []record.Finding{{
			Kind: record.KindInstruction, Disposition: record.Accepted,
			Source: "sysutils/jq/Portfile:12",
			Quote:  "# when updating this port, rev-bump\n# every dependent",
		}}
	})
	out := body(f, "")
	assert.Contains(t, out, "The comment in sysutils/jq/Portfile:12 says:\n\n```\n# when updating this port, rev-bump\n# every dependent\n```\n")

	// The bytes are untouched inside the fence: a quote that was reflowed
	// is not verbatim.
	assert.Contains(t, out, "# when updating this port, rev-bump\n# every dependent")
	// And no line of the quote sits at a Markdown heading position —
	// which is the whole point of the fence, so the check has to know
	// where the fence is. Inside one, a leading "#" is bytes; outside, it
	// is an H1.
	fenced := false
	for _, line := range strings.Split(out, "\n") {
		if strings.HasPrefix(line, "```") {
			fenced = !fenced
			continue
		}
		if !fenced && strings.HasPrefix(line, "#") && strings.Contains(line, "rev-bump") {
			t.Fatalf("a Portfile comment line renders as a heading: %q", line)
		}
	}
}

// A RECONSTRUCTION THAT DID NOT REPRODUCE THE TIP NAMES THE FILES. The
// pass that raises the hold is unattended, so the only account anybody
// gets is what is written down — data, not a sentence.
func TestADivergentReconstructionNamesThePaths(t *testing.T) {
	f := facts(func(f *Facts) {
		f.Change.Findings = []record.Finding{{
			Kind: record.KindStealth, Disposition: record.Dismissed,
			Diverged: []string{"Portfile", "files/patch-a.diff"},
		}}
	})
	assert.Contains(t, body(f, ""),
		"Re-planning this change from its own base did not reproduce the tip: Portfile, files/patch-a.diff.")
}

// AN ORDINARY BUMP CARRIES NO COHORT SECTION AT ALL.
func TestAnOrdinaryBumpHasNoCohortSection(t *testing.T) {
	out := body(facts(), "")
	assert.NotContains(t, out, "Revision bumped in this change")
	assert.NotContains(t, out, listedHeader)
	assert.NotContains(t, out, abi.Limits)
}

// THE BODY IS THE BYTES THE PUBLICATION SENDS: Gather renders it once
// and Authorize measures THAT, so `--body` is a preview of the real
// thing rather than a second rendering that could drift from it.
func TestTheBodyOnTheFactsIsWhatTheGateMeasures(t *testing.T) {
	f := facts()
	require.Equal(t, "a body", f.Body)
	long := strings.Repeat("x", f.BodyLimit+1)
	f.Body = long
	_, _, err := Authorize(f, Pace{})
	require.ErrorIs(t, err, ErrBodyTooLong)
}

// cohortFacts is a change with a headline and one revbumped dependent,
// its proposal at the disposition given.
func cohortFacts(d record.Disposition) Facts {
	return facts(func(f *Facts) {
		f.Change.Subjects = append(f.Change.Subjects, record.Subject{
			Port: "libfoo", Portdir: "devel/libfoo", Intent: "bump-revision", Target: "rev1",
			Reason: "links libjq",
		})
		f.Change.Findings = []record.Finding{{
			Kind:      record.KindABIDependents,
			Criterion: "install name libjq.1.dylib -> libjq.2.dylib",
			Ports:     []string{"libfoo"},
			Candidates: []record.Candidate{
				{Port: "libfoo", Portdir: "devel/libfoo", Proposed: true, Reason: "links libjq"},
				{Port: "libbar", Portdir: "devel/libbar", Reason: "build-only dependent"},
			},
			Disposition: d,
			At:          clock,
		}}
		f.Attempts[0].Runs["libfoo"] = record.Run{
			State: record.Passed, Content: "tree-1", At: clock,
			Links: []string{"/opt/local/bin/foo -> libjq.1.dylib"},
		}
	})
}

// THREE BLANK BOXES READ AS AN UNFILLED TEMPLATE, not as an open
// question. dockhand classifies no change as a bugfix, an enhancement or
// a security fix, and ticking one would be asserting a judgment it never
// made — so the categories stay and a sentence says whose call it is. A
// field run put a version bump in front of a reader and measured the
// other reading.
func TestTheTypeSectionSaysWhyItsBoxesAreBlank(t *testing.T) {
	out := body(facts(), "1.2.3")

	assert.Contains(t, out, "###### Type(s)")
	assert.Contains(t, out, "- [ ] bugfix", "the categories are the person's to pick from")
	assert.Contains(t, out, "dockhand does not classify changes")
	assert.NotContains(t, out, "- [x] bugfix")
	assert.NotContains(t, out, "- [x] enhancement")
	assert.NotContains(t, out, "- [x] security fix")
}

// WHAT WAS NOT CHECKED REACHES THE REVIEWER. A bump that fetched no
// distfile — a port fetched from a repository, say — had nothing to
// check its patches against, and "not checked" and "checked, and still
// where they were" are different answers. A body printing neither leaves
// a reviewer to assume the second.
//
// It reached the plan narration and stopped there, and not because
// anybody chose to stop it: the finding's kind was not a record kind, so
// the mint that would have carried it failed outright and there was
// never a record for a body to read.
func TestTheBodyStatesThePatchesItCouldNotCheck(t *testing.T) {
	f := facts(func(f *Facts) {
		f.Change.Findings = []record.Finding{{
			Kind: record.KindPatchesUnchecked, Disposition: record.Accepted,
			Criterion: "patch check unavailable: jq's 2 patchfiles were not checked against the new source because no distfile was fetched",
		}}
	})
	assert.Contains(t, body(f, "1.2.3"), "patch check unavailable: jq's 2 patchfiles were not checked")
}

// AND THE REVIEWER IS TOLD WHICH PATCH DID NOT COME OVER. A branch a
// person published past this finding is one whose patch dockhand could
// not verify carried; a body that did not say so would be the
// complete-looking artifact the old outright decline was protecting
// against, which is the whole condition on which that decline was
// relaxed.
func TestTheBodyNamesAPatchThatDidNotCarryOver(t *testing.T) {
	f := facts(func(f *Facts) {
		f.Change.Findings = []record.Finding{{
			Kind: record.KindPatchUnrelocated, Disposition: record.Proposed,
			Source:    "files/patch-foo.diff",
			Criterion: "patch not carried over: files/patch-foo.diff does not relocate onto the new source — Makefile hunk #1: its before-block occurs nowhere in the file. Refresh it by hand on the branch, then verify",
		}}
	})
	out := body(f, "1.2.3")
	assert.Contains(t, out, "files/patch-foo.diff does not relocate onto the new source")
	assert.Contains(t, out, "Makefile hunk #1")
}

// A REQUEST IS NOT A MEASUREMENT. "built and tested in a pristine VM"
// came from Ask.Test alone, and MacPorts' test phase executes nothing
// unless the Portfile sets test.run — which most ports do not. Measured
// on repgrep 0.17.1: the log goes straight from "Executing
// org.macports.test" to the next note, and the body still told reviewers
// a suite had passed.
//
// Four states, because the record carries two facts and either can be
// missing.
func TestTheBodyOnlyClaimsTestsThatCouldHaveRun(t *testing.T) {
	no := false
	for _, c := range []struct {
		name string
		run  record.Run
		want string
		not  string
	}{
		{"asked, and the port has one", record.Run{Ask: record.Ask{Test: true}, HasTests: &yes},
			"and tested in a pristine VM", ""},
		{"asked, and the port has none", record.Run{Ask: record.Ask{Test: true}, HasTests: &no},
			"the port enables no test command", "and tested"},
		{"asked, and nobody could say", record.Run{Ask: record.Ask{Test: true}},
			"whether a test suite ran was not recorded", "and tested"},
		{"not asked at all", record.Run{},
			"built in a pristine VM", "test"},
	} {
		t.Run(c.name, func(t *testing.T) {
			got := evidenceClaim("built in a pristine VM", c.run.Ask.FromSource, testEvidenceOf(c.run))
			assert.Contains(t, got, c.want)
			if c.not != "" {
				assert.NotContains(t, got, c.not)
			}
		})
	}
}

// A --no-verify PUBLICATION SAYS THE PERSON SKIPPED THE BUILD, and never
// that the machine could not run one. The two are different facts and
// only one of them is dockhand's to assert about somebody's hardware.
//
// This was measured in the field, on macports-ports#34584: a host with
// two provisioned tart bases, both free, published "no verification
// environment on the submitting machine" to reviewers, because
// --no-verify used to write ToBranch and the body read the DESTINATION
// as if it were the ASK. Making --no-verify and --to-pr compose turned a
// sentence that had been true into one that was false, in public.
func TestAnUnverifiedPublicationBlamesTheAskAndNotTheMachine(t *testing.T) {
	for _, dest := range []record.Destination{record.ToPublished, record.ToBranch, record.ToVerdict} {
		f := Facts{Change: record.Change{Destination: dest, Unverified: true}}
		line := unrunLine(f)
		assert.Contains(t, line, "not pre-verified",
			"%s: the person asked for no build, whatever the change was bound for", dest)
		assert.NotContains(t, line, "submitting machine",
			"%s: dockhand does not diagnose a machine it never asked", dest)
	}
}

// THE BODY NEVER DIAGNOSES THE MACHINE, because nothing it is given
// measures one. This test asserted the opposite a commit ago — that the
// machine's sentence "survives for the case it is true of" — and the
// case it was true of is not one this function can pick out.
//
// Zero attempts is reached three ways: a host with no verifier, a person
// who asked for no build, and a change whose passing attempt was
// adopted and so invisible to a gather keyed on the change id. The
// sentence was published for the second and third causes on a machine
// holding two provisioned bases (macports-ports#34584, #34586). What is
// actually known is that no run is recorded for these bytes, so that is
// what it says.
func TestTheBodyDoesNotDiagnoseTheMachine(t *testing.T) {
	f := Facts{Change: record.Change{Destination: record.ToPublished}}
	line := unrunLine(f)
	assert.Contains(t, line, "nothing has been run for this commit's content")
	assert.NotContains(t, line, "submitting machine",
		"a body may not assert a fact about hardware it never measured")
}

// THE VERDICT NAMES THE COMMIT IT IS ABOUT. "Verified" with no sha is a
// claim a reviewer cannot check: a branch moves, and a body that vouches
// for whatever sits at its head today vouches for something else
// tomorrow. It is the first line and the bold is the one thing scanned
// for.
func TestTheVerdictLineNamesItsCommit(t *testing.T) {
	out := body(facts(), "1.2.3")
	assert.Contains(t, out, "Submitted by [dockhand](")
	assert.Contains(t, out, "Build **verified** at commit `aaaa`")
	assert.Contains(t, out, "\n[dockhand](https://github.com/herbygillot/dockhand) 1.2.3\n",
		"the footer is the tool and its build, and no sentence about automation")
	assert.NotContains(t, out, "Automated by")

	// And it is named ONCE: provenance keeps the half a reviewer cannot
	// get anywhere else — how current the tree underneath was.
	assert.NotContains(t, out, "Branch head `aaaa`")
	assert.Contains(t, out, "Written against the ports tree")
}

// AN UNVERIFIED BODY SAYS SO IN THE SAME PLACE, so the one line a
// reviewer scans for is in the same position whatever the answer, and
// keeps its branch head — nothing above it named the commit.
func TestAnUnverifiedBodySaysSoInTheSamePlace(t *testing.T) {
	out := body(facts(func(f *Facts) { f.Attempts = nil }), "")
	assert.Contains(t, out, "Build **not** verified")
	assert.NotContains(t, out, "**verified** at commit")
	assert.Contains(t, out, "Branch head `aaaa`")
}

// THE ENVIRONMENT IS REPORTED ONLY WHERE THE PROVIDER REPORTED IT. A
// reviewer told "built in a pristine VM" is owed the machine it was
// pristine on — but "Tahoe" is a release and not a point version, and
// dockhand may say only what the guest actually answered.
func TestTheEnvironmentIsNamedOnlyWhenItWasMeasured(t *testing.T) {
	measured := facts(func(f *Facts) {
		for i := range f.Attempts {
			f.Attempts[i].OS = "26.6.2 (25G83)"
			f.Attempts[i].Xcode = "Xcode 26.6"
		}
	})
	out := body(measured, "")
	assert.Contains(t, out, "on macOS 26.6.2 (25G83), Xcode 26.6.")

	// A provider that said nothing produces no line at all, rather than a
	// plausible sentence nobody measured.
	silent := body(facts(), "")
	assert.NotContains(t, silent, "  — on macOS")

	// Half an answer is still an answer, and the half that is missing is
	// simply absent.
	partial := facts(func(f *Facts) {
		for i := range f.Attempts {
			f.Attempts[i].OS = "26.6.2 (25G83)"
		}
	})
	out = body(partial, "")
	assert.Contains(t, out, "on macOS 26.6.2 (25G83).")
	assert.NotContains(t, out, "Xcode")
}
