ALTER TABLE jobs ADD COLUMN wait_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE attempts ADD COLUMN wait_kind TEXT NOT NULL DEFAULT '';
ALTER TABLE resources ADD COLUMN wait_kind TEXT NOT NULL DEFAULT '';
PRAGMA user_version=19;
