// Code generated by internal/macports/info/internal/gen. DO NOT EDIT.

package info

// Field identifies one field of Semantic. The set is closed, and
// String speaks MacPorts' own option names — these are the canonical
// field identifiers shared by everything that names port metadata,
// and the vocabulary a plan's predicted delta is recorded in.
//
// The order is Semantic's own declaration order, which makes it the
// canonical order of a delta's field changes: two equal deltas
// compare equal deterministically because the table is walked in it.
type Field int

const (
	FieldName Field = iota
	FieldVersion
	FieldRevision
	FieldEpoch
	FieldCategories
	FieldLicense
	FieldMaintainers
	FieldPlatforms
	FieldDescription
	FieldHomepage
	FieldLongDescription
	FieldDistfiles
	FieldChecksums
	FieldDependsFetch
	FieldDependsExtract
	FieldDependsPatch
	FieldDependsBuild
	FieldDependsLib
	FieldDependsRun
	FieldDependsTest
)

// String is the MacPorts option name this field answers to.
func (f Field) String() string {
	switch f {
	case FieldName:
		return "name"
	case FieldVersion:
		return "version"
	case FieldRevision:
		return "revision"
	case FieldEpoch:
		return "epoch"
	case FieldCategories:
		return "categories"
	case FieldLicense:
		return "license"
	case FieldMaintainers:
		return "maintainers"
	case FieldPlatforms:
		return "platforms"
	case FieldDescription:
		return "description"
	case FieldHomepage:
		return "homepage"
	case FieldLongDescription:
		return "long_description"
	case FieldDistfiles:
		return "distfiles"
	case FieldChecksums:
		return "checksums"
	case FieldDependsFetch:
		return "depends_fetch"
	case FieldDependsExtract:
		return "depends_extract"
	case FieldDependsPatch:
		return "depends_patch"
	case FieldDependsBuild:
		return "depends_build"
	case FieldDependsLib:
		return "depends_lib"
	case FieldDependsRun:
		return "depends_run"
	case FieldDependsTest:
		return "depends_test"
	}
	return "unknown field"
}

// Fields is every Field, in canonical order. It is what a caller
// iterating the closed set walks, so that adding a field extends
// the walk instead of needing the walk's bounds edited — and so
// that a caller cannot silently miss a field appended after
// whichever constant it had hard-coded as the end.
func Fields() []Field {
	return []Field{
		FieldName,
		FieldVersion,
		FieldRevision,
		FieldEpoch,
		FieldCategories,
		FieldLicense,
		FieldMaintainers,
		FieldPlatforms,
		FieldDescription,
		FieldHomepage,
		FieldLongDescription,
		FieldDistfiles,
		FieldChecksums,
		FieldDependsFetch,
		FieldDependsExtract,
		FieldDependsPatch,
		FieldDependsBuild,
		FieldDependsLib,
		FieldDependsRun,
		FieldDependsTest,
	}
}

// semanticTable is the single source of field extraction: Diff,
// Values equality, and any field-addressed access all read a
// Semantic through it. It is generated from the struct, so a field
// that is not here is a field that is not in Semantic.
var semanticTable = []struct {
	field Field
	get   func(Semantic) []string
}{
	{FieldName, func(v Semantic) []string { return scalar(v.Name) }},
	{FieldVersion, func(v Semantic) []string { return scalar(v.Version) }},
	{FieldRevision, func(v Semantic) []string { return scalar(v.Revision) }},
	{FieldEpoch, func(v Semantic) []string { return scalar(v.Epoch) }},
	{FieldCategories, func(v Semantic) []string { return v.Categories }},
	{FieldLicense, func(v Semantic) []string { return v.License }},
	{FieldMaintainers, func(v Semantic) []string { return v.Maintainers }},
	{FieldPlatforms, func(v Semantic) []string { return v.Platforms }},
	{FieldDescription, func(v Semantic) []string { return scalar(v.Description) }},
	{FieldHomepage, func(v Semantic) []string { return scalar(v.Homepage) }},
	{FieldLongDescription, func(v Semantic) []string { return scalar(v.LongDescription) }},
	{FieldDistfiles, func(v Semantic) []string { return v.Distfiles }},
	{FieldChecksums, func(v Semantic) []string { return v.Checksums }},
	{FieldDependsFetch, func(v Semantic) []string { return v.Depends.Fetch }},
	{FieldDependsExtract, func(v Semantic) []string { return v.Depends.Extract }},
	{FieldDependsPatch, func(v Semantic) []string { return v.Depends.Patch }},
	{FieldDependsBuild, func(v Semantic) []string { return v.Depends.Build }},
	{FieldDependsLib, func(v Semantic) []string { return v.Depends.Lib }},
	{FieldDependsRun, func(v Semantic) []string { return v.Depends.Run }},
	{FieldDependsTest, func(v Semantic) []string { return v.Depends.Test }},
}

// The pins below are the enforcement, and they are the reason this
// file is generated at all. An UNKEYED composite literal must give a
// value for every field of its struct, so a field added to one of
// these types stops the package from compiling until the generator
// has run again and given that field a Field constant and a row in
// semanticTable. Go offers no exhaustiveness over struct fields;
// this is the closest thing to it, and it is a build failure rather
// than a review catch or a runtime surprise (D8).
//
// If one of these is failing to compile: run
// `go generate ./internal/macports/info` and commit the result.
var _ = Semantic{"", "", "", "", nil, nil, nil, nil, "", "", "", nil, nil, Depends{}}
var _ = Depends{nil, nil, nil, nil, nil, nil, nil}
